classes:
- system.linux.system.single
- system.linux.system.repo.mcp.extra
- system.linux.system.repo.mcp.salt #FIXME
- system.linux.system.repo.saltstack.xenial
- system.linux.system.repo.ubuntu
- system.openssh.server.team.members.mlos
- system.openssh.server.team.tcpcloud
- system.openssh.server.team.lab
- cluster.ceph_ha.ceph
- cluster.overrides
parameters:
  _param:
    salt_version: '2016.3'
    # infra service addresses
    infra_config_hostname: cfg01
    infra_config_address: 10.0.10.10
    infra_config_deploy_address: 10.0.10.10

    cluster_domain: ceph_ha.local
    cluster_name: ceph_ha
    apt_mk_version: nightly
    primary_interface: ens3

    # default - will be change in overrides
    ceph_mon_node01_address: 10.0.10.11
    ceph_mon_node02_address: 10.0.10.12
    ceph_mon_node03_address: 10.0.10.13
  linux:
    network:
      host:
        cfg01:
          address: ${_param:infra_config_address}
          names:
          - ${_param:infra_config_hostname}
          - ${_param:infra_config_hostname}.${_param:cluster_domain}
      interface:
        primary_interface:
          enabled: true
          type: eth
          proto: dhcp
          #proto: static
          #name: ${_param:primary_interface}
          #address: ${_param:single_address}
          #netmask: 255.255.255.0
    system:
      name: ${_param:infra_config_hostname}
      domain: ${_param:cluster_domain}
